trigger:
  branches:
    include:
      - '*'  # Trigger on all pushes
  #paths:
   # include:
    #  - '**'  # Trigger on changes to any file


steps:
  - checkout: self

  - script: |
      git config --global credential.helper store
      git config --global user.email "008458743@coyote.csusb.edu"
      git config --global user.name "008458743-csusb"
      git clone https://008458743-csusb:$(GitHubPAT)@github.com/SEC-Spring2024-Team-1/team_1_project-6550.git team_1_project-6550
      cd team_1_project-6550
      git config --global user.email "008458743@coyote.csusb.edu"
      git config --global user.name "008458743"
      git remote add azure https://$(AzurePAT)@dev.azure.com/008426399/SE_TEAM_01/_git/team_1_project-6550
      git fetch azure --prune  # Fetch all branches from Azure Repo and prune old references
      for branch in $(git branch -r | grep -v HEAD); do  # Iterate over all branches
          branch_name=$(echo $branch | sed 's/.*\///')  # Extract branch name
          git checkout -B $branch_name azure/$branch_name  # Checkout the branch
          git push origin $branch_name  # Push the branch to GitHub
      done
    displayName: 'Sync github and azure repos'