trigger:
  branches:
    include:
      - '*'  # Trigger on all pushes

pr:
- '*'

jobs:
- job: SyncRepos
  displayName: 'Sync GitHub and Azure Repos'
  pool:
    vmImage: 'ubuntu-latest'

  steps:
  - checkout: self

  - script: |
      git config --global user.email "008458743@coyote.csusb.edu"
      git config --global user.name "008458743-csusb"

      git clone https://008458743-csusb:$(GitHubPAT)@github.com/SEC-Spring2024-Team-1/team_1_project-6550.git team_1_project-6550
      cd team_1_project-6550
      git config --global user.email "008458743@coyote.csusb.edu"
      git config --global user.name "008458743"
      git remote add azure https://$(AzurePAT)@dev.azure.com/008426399/SE_TEAM_01/_git/team_1_project-6550.git
      git fetch azure --prune

      for branch in $(git branch -r | grep -v HEAD); do
          branch_name=$(echo $branch | sed 's/.*\///')
          git checkout -B $branch_name azure/$branch_name || git checkout $branch_name
          git merge azure/$branch_name --allow-unrelated-histories -m "Merge branch '$branch_name' from Azure"
          git push origin $branch_name
      done
    displayName: 'Sync GitHub and Azure Repos'
